# Generated by Django 6.0.1 on 2026-04-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='goal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
