# Generated by Django 6.0.1 on 2026-04-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, verbose_name='Temps passé (heures)'),
        ),
    ]
