# Generated by Django 6.0.1 on 2026-04-07 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
        ('tickets', '0002_ticket_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='sprints.sprint'),
        ),
    ]
